name: example
description: PathXp example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nes_ui:
    git:
      url: https://github.com/erickzanardo/nes_ui.git
  pathxp:
    path: ../

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
